### ISSUE TITLE
nfl opto errors

### ISSUE THREAD

**Issue by Shiner36** [chanzer0/NFL-DFS-Tools#2]
Hello and thank you for all the tools you have set up. Wondering if the error I received below when attempting to run NFL opto process is due to user error on my end or if they are potentially still a work in progress?

File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\main.py", line 5, in <module>
    from nfl_optimizer import *
  File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\nfl_optimizer.py", line 1, in <module>
    import json5 as json
ModuleNotFoundError: No module named 'json5'

**Comment by bjungwirth** [comment]
gotta pip install json5 in your command line. we probably should just include a requirements.txt @chanzer0

**Comment by Shiner36** [comment]
thank you. playing around with it and the sims are using NBA roster spots in the headers and most lineups are spitting out 2 qbs in the same lu

**Comment by bjungwirth** [comment]
use my fork for sims until it gets merged https://github.com/bjungwirth/NFL-DFS-Tools

**Comment by bjungwirth** [comment]
@Shiner36 we merged the forks, should be able to run the opto and sim from the same repo. let us know if you have any issues.

**Comment by chanzer0** [comment]
^ https://discord.gg/BCjrz7eVkQ
